version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/home/node/code:cached
      - workspaces-data:/home/node/workspaces
    command: sleep infinity

volumes:
  workspaces-data:
