version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/home/vscode/code:cached
      - workspaces-data:/home/vscode/workspaces
    command: sleep infinity
    network_mode: service:db

  db:
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_USER: mariadb

volumes:
  mariadb-data:
  workspaces-data:
